### ISSUE TITLE
Make the font of the buttons customisable.

### ISSUE THREAD

**Issue by TakenagaT** [guide-me/GuideMe#3]

**Comment by philormand** [comment]
Added 5 new attributes to button
fontName Font Name
fontHeight Height of font
bgColor1 Color of background or top color for graduated fill
bgColor2 bottom Color for graduated fill
fontColor font color

Colors supported
white
black
dark_red
dark_green
dark_yellow
dark_blue
dark_magenta
dark_cyan
dark_gray
gray
red
green
yellow
blue
magenta
cyan

**Comment by philormand** [comment]
<Button target="Page(5..6)" bgColor1="red" bgColor2="dark_red" fontColor="green" fontName="Tahoma" fontHeight="25" >Page 5 or 6</Button>
      <Button target="Page(3..4)" bgColor1="green" bgColor2="dark_green" fontColor="red" fontName="Tahoma" fontHeight="25" >Page 3 or 4</Button>

**Comment by meson1** [comment]
How about allowing buttons to be styled via CSS?  That would be the ultimate formatting, wouldn't it?  On the <Button /> element, add a type= attribute.  So that in the CSS you can add your button type and format it any way you like.

So XML of:
<Button target="Page7" type="bigredbutton">Panic</Button>

would translate into html like this:
<input type="bigredbutton" value="Panic" ...etc ... />

And the author then adds the appropriate CSS into the CSS:
#bigredbutton{
    background-color: #c44;
    -moz-border-radius: 5px;
    -webkit-border-radius: 5px;
    border-radius:6px;
    color: #a00;
    font-family: 'Oswald';
    font-size: 20px;
    text-decoration: none;
    cursor: pointer;
    border:none;
}
